2025-03-07 03:44:25 | INFO | Инициализация SessionManager
2025-03-07 03:44:25 | DEBUG | Загружен существующий ключ шифрования
2025-03-07 03:45:04 | ERROR | Ошибка при подтверждении аккаунтов: 'FSMContext' object has no attribute 'proxy'
Traceback (most recent call last):

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1706, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x0000023F4D05F920>
    │       └ <function run at 0x0000023F41685BC0>
    └ <module 'asyncio' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000023F4CBD2140>
           │      └ <function Runner.run at 0x0000023F43A26980>
           └ <asyncio.runners.Runner object at 0x0000023F4D0267B0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py:1698> wait_for=...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000023F43A24540>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000023F4D0267B0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000023F43A244A0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000023F43A262A0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000023F43951260>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,)}
                     │    │           │    └ Update(update_id=334263734, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>
                     │    └ <function Dispatcher.feed_update at 0x0000023F4BE4F1A0>
                     └ <Dispatcher '0x23f4d025010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000023F4BE4D9E0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000023F4D02E0D0>
                     └ <Dispatcher '0x23f4d025010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263734, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000023F4D025D30>, functools...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263734, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000023F4D025FD0>, <function TelegramEventObserver...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263734, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x0000023F4D07A5C0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │             └ Update(update_id=334263734, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x0000023F4D07AD40>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x23f4d025010'>>, Update(update_id=334263734, messa...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='8223005365781665358', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x0000023F4BE4E7A0>
                 └ <Dispatcher '0x23f4d025010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='8223005365781665358', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000023F4D0AEA20>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000023F4BE4D9E0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000023F4CFDDBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000023F4BE4E840>
                 └ <Dispatcher '0x23f4d025010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='8223005365781665358', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                     │        └ <function TelegramEventObserver.trigger at 0x0000023F4BE4DB20>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000023F4CFDDBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x23f4d025010'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000023F4CEB3E00>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='8223005365781665358', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 └ <function CallableObject.call at 0x0000023F4D0ADBC0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function confirm_accounts at 0x0000023F4D05DD00>, CallbackQuery(id='8223005365781665358', from_user=User(i...

> File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 785, in confirm_accounts
    async with state.proxy() as data:
               └ <aiogram.fsm.context.FSMContext object at 0x0000023F4E376DD0>

AttributeError: 'FSMContext' object has no attribute 'proxy'
