2025-03-07 03:40:11 | INFO | Инициализация SessionManager
2025-03-07 03:40:11 | DEBUG | Загружен существующий ключ шифрования
2025-03-07 03:40:20 | ERROR | Ошибка при выборе группы: 1 validation error for InlineKeyboardMarkup
inline_keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
Traceback (most recent call last):

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1714, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x000001702C863880>
    │       └ <function run at 0x000001701FDF5B20>
    └ <module 'asyncio' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x000001702B4022C0>
           │      └ <function Runner.run at 0x00000170222268E0>
           └ <asyncio.runners.Runner object at 0x000001702B8567B0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py:1706> wait_for=...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000170222244A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001702B8567B0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000017022224400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000017022226200>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000170221511C0>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,)}
                     │    │           │    └ Update(update_id=334263721, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x000001702B6DFE00>
                     │    └ <function Dispatcher.feed_update at 0x000001702A66B100>
                     └ <Dispatcher '0x1702b855010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x000001702A669940>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000001702B85E0D0>
                     └ <Dispatcher '0x1702b855010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263721, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x000001702B855D30>, functools...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263721, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x000001702B855FD0>, <function TelegramEventObserver...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263721, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x000001702C863F60>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │             └ Update(update_id=334263721, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x000001702C8ACD60>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x1702b855010'>>, Update(update_id=334263721, messa...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='8223005366784218553', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x000001702A66A700>
                 └ <Dispatcher '0x1702b855010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='8223005366784218553', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x000001702C8ACEA0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x000001702A669940>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000001702B80DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x000001702A66A7A0>
                 └ <Dispatcher '0x1702b855010'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='8223005366784218553', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                     │        └ <function TelegramEventObserver.trigger at 0x000001702A669A80>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000001702B80DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x1702b855010'>, 'bots': (<aiogram.client.bot.Bot object at 0x000001702B6DFE00>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='8223005366784218553', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 └ <function CallableObject.call at 0x000001702C8ADB20>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function select_group at 0x000001702C861760>, CallbackQuery(id='8223005366784218553', from_user=User(id=19...

> File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 664, in select_group
    markup = types.InlineKeyboardMarkup()
             │     └ <class 'aiogram.types.inline_keyboard_markup.InlineKeyboardMarkup'>
             └ <module 'aiogram.types' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\aiogram\\type...

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     │    │                      │               │                   └ InlineKeyboardMarkup()
                     │    │                      │               └ {}
                     │    │                      └ <method 'validate_python' of 'pydantic_core._pydantic_core.SchemaValidator' objects>
                     │    └ SchemaValidator(title="InlineKeyboardMarkup", validator=Model(
                     │          ModelValidator {
                     │              revalidate: Never,
                     │              valida...
                     └ InlineKeyboardMarkup()

pydantic_core._pydantic_core.ValidationError: 1 validation error for InlineKeyboardMarkup
inline_keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
