2025-03-07 03:26:17 | ERROR | [Этап 4/5] ❌ Ошибка при отправке фото: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'temp_media/photo_20250307_032616.jpg'
2025-03-07 03:26:17 | ERROR | [Этап 4/5] ❌ Ошибка при отправке сообщения: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'temp_media/photo_20250307_032616.jpg'
2025-03-07 03:26:37 | ERROR | Ошибка при подтверждении аккаунтов: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Traceback (most recent call last):

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1688, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x000002C2BBAF3880>
    │       └ <function run at 0x000002C2AF125B20>
    └ <module 'asyncio' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x000002C2BA68E200>
           │      └ <function Runner.run at 0x000002C2B15168E0>
           └ <asyncio.runners.Runner object at 0x000002C2BAAE6660>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py:1680> wait_for=...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002C2B15144A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002C2BAAE6660>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000002C2B1514400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002C2B1516200>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002C2B13451C0>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,)}
                     │    │           │    └ Update(update_id=334263665, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
                     │    └ <function Dispatcher.feed_update at 0x000002C2B990F100>
                     └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x000002C2B990D940>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAAEE050>
                     └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263665, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x000002C2BAAE5BE0>, functools...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263665, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x000002C2BAAE5E80>, <function TelegramEventObserver...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263665, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x000002C2BBF10B80>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │             └ Update(update_id=334263665, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x000002C2BBF10CC0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x2c2baae4ec0'>>, Update(update_id=334263665, messa...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='8223005367482816427', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x000002C2B990E700>
                 └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='8223005367482816427', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x000002C2BBF10900>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x000002C2B990D940>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAA9DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x000002C2B990E7A0>
                 └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='8223005367482816427', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                     │        └ <function TelegramEventObserver.trigger at 0x000002C2B990DA80>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAA9DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='8223005367482816427', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 └ <function CallableObject.call at 0x000002C2BBF10C20>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function confirm_accounts at 0x000002C2BBAF1C60>, CallbackQuery(id='8223005367482816427', from_user=User(i...

> File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 861, in confirm_accounts
    await callback.message.edit_text(
          │        │       └ <function Message.edit_text at 0x000002C2B2332520>
          │        └ Message(message_id=1440, date=datetime.datetime(2025, 3, 6, 22, 25, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1914567632, type='p...
          └ CallbackQuery(id='8223005367482816427', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
                 │   └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
                 └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
                 │    │       │     │               └ None
                 │    │       │     └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
                 │    │       └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
                 │    └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x000002C2BAAE5010>
                 └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
           │    │                   │          │    └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
           │    │                   │          └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
           │    │                   └ functools.partial(<bound method AiohttpSession.make_request of <aiogram.client.session.aiohttp.AiohttpSession object at 0x000...
           │    └ ~TelegramType
           └ <function cast at 0x000002C2B14FF9C0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               │    └ <function BaseSession.check_response at 0x000002C2B986FBA0>
               └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x000002C2BAAE5010>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
          │                         │               └ 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          │                         └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
          └ <class 'aiogram.exceptions.TelegramBadRequest'>

aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-03-07 03:27:00 | ERROR | Ошибка при подтверждении аккаунтов: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Traceback (most recent call last):

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1688, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x000002C2BBAF3880>
    │       └ <function run at 0x000002C2AF125B20>
    └ <module 'asyncio' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x000002C2BA68E200>
           │      └ <function Runner.run at 0x000002C2B15168E0>
           └ <asyncio.runners.Runner object at 0x000002C2BAAE6660>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py:1680> wait_for=...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002C2B15144A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002C2BAAE6660>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000002C2B1514400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002C2B1516200>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002C2B13451C0>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,)}
                     │    │           │    └ Update(update_id=334263664, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
                     │    └ <function Dispatcher.feed_update at 0x000002C2B990F100>
                     └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x000002C2B990D940>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAAEE050>
                     └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263664, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x000002C2BAAE5BE0>, functools...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263664, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x000002C2BAAE5E80>, <function TelegramEventObserver...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │       └ Update(update_id=334263664, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x000002C2B36C6660>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │             └ Update(update_id=334263664, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x000002C2BBEE6160>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x2c2baae4ec0'>>, Update(update_id=334263664, messa...
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='8223005368217878420', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x000002C2B990E700>
                 └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='8223005368217878420', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x000002C2BBEE6980>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x000002C2B990D940>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAA9DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x000002C2B990E7A0>
                 └ <Dispatcher '0x2c2baae4ec0'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='8223005368217878420', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                     │        └ <function TelegramEventObserver.trigger at 0x000002C2B990DA80>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x000002C2BAA9DBF0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x2c2baae4ec0'>, 'bots': (<aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='8223005368217878420', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...
                 └ <function CallableObject.call at 0x000002C2BBEE6480>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function confirm_accounts at 0x000002C2BBAF1C60>, CallbackQuery(id='8223005368217878420', from_user=User(i...

> File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 861, in confirm_accounts
    await callback.message.edit_text(
          │        │       └ <function Message.edit_text at 0x000002C2B2332520>
          │        └ Message(message_id=1440, date=datetime.datetime(2025, 3, 6, 22, 25, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1914567632, type='p...
          └ CallbackQuery(id='8223005368217878420', from_user=User(id=1914567632, is_bot=False, first_name='Нуритдинов Шохрух', last_name...

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
                 │   └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
                 └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
                 │    │       │     │               └ None
                 │    │       │     └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
                 │    │       └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
                 │    └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x000002C2BAAE5010>
                 └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
           │    │                   │          │    └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
           │    │                   │          └ <aiogram.client.bot.Bot object at 0x000002C2BA9B3CB0>
           │    │                   └ functools.partial(<bound method AiohttpSession.make_request of <aiogram.client.session.aiohttp.AiohttpSession object at 0x000...
           │    └ ~TelegramType
           └ <function cast at 0x000002C2B14FF9C0>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               │    └ <function BaseSession.check_response at 0x000002C2B986FBA0>
               └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x000002C2BAAE5010>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
          │                         │               └ 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          │                         └ EditMessageText(text='📊 Результаты отправки:\n✅ Успешно: 7\n❌ Ошибок: 0', business_connection_id=None, chat_id=1914567632, me...
          └ <class 'aiogram.exceptions.TelegramBadRequest'>

aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-03-07 03:30:31 | ERROR | [Этап 4/5] ❌ Ошибка при отправке фото: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'temp_media/photo_20250307_033031.jpg'
2025-03-07 03:30:31 | ERROR | [Этап 4/5] ❌ Ошибка при отправке сообщения: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'temp_media/photo_20250307_033031.jpg'
